[package]
name = "classify-client"
version = "0.1.0"
authors = ["Michael Cooper <mcooper@mozilla.com>"]
edition = "2018"

[dependencies]
actix = "^0.7.6"
actix-web = "^0.7.14"
cadence = "^0.16.0"
chrono = { version = "^0.4", features = ["serde"] }
envy = "^0.3.3"
futures = "*"
lazy_static = "^1.2.0"
ipnet = { version = "^2", features = ["serde"] }
maxminddb = "^0.13.0"
regex = "^1.1.0"
sentry = "^0.12.1"
sentry-actix = "^0.12.1"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "^1.0.33"
slog = "^2.4"
slog_derive = "0.1.1"
slog-async = "2.3.0"
slog-json = "2.3.0"
slog-term = "2.4.0"
slog-mozlog-json = "0.1.0"